/* eslint-disable @typescript-eslint/naming-convention -- keys are note names (Do♯, Ré♭, …) */

export type ScaleQuality = "major" | "minor" | "harmonicMinor" | "harmonicMajor";

export const SCALE_ROOT_NAMES = [
  "Do",
  "Do♯",
  "Ré♭",
  "Ré",
  "Ré♯",
  "Mi♭",
  "Mi",
  "Fa",
  "Fa♯",
  "Sol♭",
  "Sol",
  "Sol♯",
  "La♭",
  "La",
  "La♯",
  "Si♭",
  "Si",
  "Do♭",
] as const;

export type ScaleRootName = (typeof SCALE_ROOT_NAMES)[number];

export interface ScaleNoteData {
  name: string;
  octave: number;
  midi: number;
  stringIndex: number;
  fretIndex: number;
  isPentatonic?: boolean;
  isBlue?: boolean;
}

export const SCALE_NOTES: Record<ScaleQuality, Record<ScaleRootName, ScaleNoteData[]>> = {
  major: {
    "Do": [
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isBlue: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isBlue: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8, isPentatonic: true },
    ],
    "Do♯": [
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isBlue: true },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isBlue: true },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Si♯", octave: 4, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
    ],
    "Ré♭": [
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isBlue: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isBlue: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Ré♭", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
    ],
    "Ré": [
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isBlue: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isBlue: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10, isPentatonic: true },
    ],
    "Ré♯": [
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isBlue: true },
      { name: "Fa𝄪", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Do𝄪", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isBlue: true },
      { name: "Fa𝄪", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Si♯", octave: 4, midi: 72, stringIndex: 5, fretIndex: 8, isPentatonic: true },
      { name: "Do𝄪", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11, isPentatonic: true },
    ],
    "Mi♭": [
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isBlue: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isBlue: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8, isPentatonic: true },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
      { name: "Mi♭", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11, isPentatonic: true },
    ],
    "Mi": [
      { name: "Mi", octave: 2, midi: 40, stringIndex: 0, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2, isPentatonic: true },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3, isBlue: true },
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isBlue: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isBlue: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
      { name: "Mi", octave: 5, midi: 76, stringIndex: 5, fretIndex: 12, isPentatonic: true },
    ],
    "Fa": [
      { name: "Fa", octave: 2, midi: 41, stringIndex: 0, fretIndex: 1, isPentatonic: true },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3, isPentatonic: true },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isBlue: true },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isBlue: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
    ],
    "Fa♯": [
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2, isPentatonic: true },
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isBlue: true },
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isBlue: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
    ],
    "Sol♭": [
      { name: "Sol♭", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2, isPentatonic: true },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "Si𝄫", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isBlue: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isBlue: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
    ],
    "Sol": [
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isBlue: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isBlue: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
    ],
    "Sol♯": [
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isBlue: true },
      { name: "Si♯", octave: 2, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Fa𝄪", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isBlue: true },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Fa𝄪", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
    ],
    "La♭": [
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2, isBlue: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isBlue: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
    ],
    "La": [
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isBlue: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isBlue: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
    ],
    "La♯": [
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Si♯", octave: 2, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isBlue: true },
      { name: "Do𝄪", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Fa𝄪", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "Sol𝄪", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isBlue: true },
      { name: "Do𝄪", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Fa𝄪", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "Sol𝄪", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
    ],
    "Si♭": [
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isBlue: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isBlue: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
    ],
    "Si": [
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isBlue: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isBlue: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
    ],
    "Do♭": [
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isBlue: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isBlue: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
    ],
  },
  minor: {
    "Do": [
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isBlue: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isBlue: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8, isPentatonic: true },
    ],
    "Do♯": [
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isBlue: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isBlue: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
    ],
    "Ré♭": [
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La𝄫", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isBlue: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "La𝄫", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isBlue: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "Si𝄫", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
      { name: "Ré♭", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
    ],
    "Ré": [
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isBlue: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isBlue: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8, isPentatonic: true },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10, isPentatonic: true },
    ],
    "Ré♯": [
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isBlue: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isBlue: true },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11, isPentatonic: true },
    ],
    "Mi♭": [
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isBlue: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "Si𝄫", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isBlue: true },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Ré♭", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9, isPentatonic: true },
      { name: "Mi♭", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11, isPentatonic: true },
    ],
    "Mi": [
      { name: "Mi", octave: 2, midi: 40, stringIndex: 0, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isBlue: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isBlue: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isBlue: true },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10, isPentatonic: true },
      { name: "Mi", octave: 5, midi: 76, stringIndex: 5, fretIndex: 12, isPentatonic: true },
    ],
    "Fa": [
      { name: "Fa", octave: 2, midi: 41, stringIndex: 0, fretIndex: 1, isPentatonic: true },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3 },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2, isBlue: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isBlue: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
    ],
    "Fa♯": [
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2, isPentatonic: true },
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isBlue: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isBlue: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
    ],
    "Sol♭": [
      { name: "Sol♭", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2, isPentatonic: true },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "Si𝄫", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Ré𝄫", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isBlue: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Ré𝄫", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isBlue: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
    ],
    "Sol": [
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isBlue: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isBlue: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
    ],
    "Sol♯": [
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isBlue: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isBlue: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
    ],
    "La♭": [
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4, isPentatonic: true },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isBlue: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isBlue: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
    ],
    "La": [
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0, isPentatonic: true },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3, isPentatonic: true },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isBlue: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0, isPentatonic: true },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1, isPentatonic: true },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isBlue: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3, isPentatonic: true },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
    ],
    "La♯": [
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Si♯", octave: 2, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isBlue: true },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isBlue: true },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
    ],
    "Si♭": [
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1, isPentatonic: true },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4, isPentatonic: true },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1, isPentatonic: true },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isBlue: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isPentatonic: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1, isPentatonic: true },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3, isPentatonic: true },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2, isPentatonic: true },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4, isPentatonic: true },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isBlue: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isPentatonic: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4, isPentatonic: true },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6, isPentatonic: true },
    ],
    "Si": [
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isBlue: true },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isBlue: true },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
    ],
    "Do♭": [
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2, isPentatonic: true },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0, isPentatonic: true },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2, isPentatonic: true },
      { name: "Sol𝄫", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3, isBlue: true },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4, isPentatonic: true },
      { name: "La𝄫", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2, isPentatonic: true },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0, isPentatonic: true },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3, isPentatonic: true },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0, isPentatonic: true },
      { name: "Sol𝄫", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1, isBlue: true },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2, isPentatonic: true },
      { name: "La𝄫", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Si𝄫", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5, isPentatonic: true },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7, isPentatonic: true },
    ],
  },
  harmonicMinor: {
    "Do": [
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
    ],
    "Do♯": [
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♯", octave: 4, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
    ],
    "Ré♭": [
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si𝄫", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Ré♭", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
    ],
    "Ré": [
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
    ],
    "Ré♯": [
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do𝄪", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do𝄪", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
    ],
    "Mi♭": [
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
      { name: "Mi♭", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
    ],
    "Mi": [
      { name: "Mi", octave: 2, midi: 40, stringIndex: 0, fretIndex: 0 },
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
      { name: "Mi", octave: 5, midi: 76, stringIndex: 5, fretIndex: 12 },
    ],
    "Fa": [
      { name: "Fa", octave: 2, midi: 41, stringIndex: 0, fretIndex: 1 },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3 },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
    ],
    "Fa♯": [
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
    ],
    "Sol♭": [
      { name: "Sol♭", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "Si𝄫", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
    ],
    "Sol": [
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
    ],
    "Sol♯": [
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa𝄪", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa𝄪", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
    ],
    "La♭": [
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
    ],
    "La": [
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
    ],
    "La♯": [
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Si♯", octave: 2, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol𝄪", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol𝄪", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
    ],
    "Si♭": [
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
    ],
    "Si": [
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
    ],
    "Do♭": [
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La𝄫", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La𝄫", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7 },
    ],
  },
  harmonicMajor: {
    "Do": [
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
    ],
    "Do♯": [
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♯", octave: 4, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
    ],
    "Ré♭": [
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si𝄫", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si𝄫", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Ré♭", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
    ],
    "Ré": [
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♯", octave: 5, midi: 73, stringIndex: 5, fretIndex: 9 },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
    ],
    "Ré♯": [
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa𝄪", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do𝄪", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa𝄪", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do𝄪", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
    ],
    "Mi♭": [
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Ré", octave: 5, midi: 74, stringIndex: 5, fretIndex: 10 },
      { name: "Mi♭", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
    ],
    "Mi": [
      { name: "Mi", octave: 2, midi: 40, stringIndex: 0, fretIndex: 0 },
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
      { name: "Do", octave: 5, midi: 72, stringIndex: 5, fretIndex: 8 },
      { name: "Ré♯", octave: 5, midi: 75, stringIndex: 5, fretIndex: 11 },
      { name: "Mi", octave: 5, midi: 76, stringIndex: 5, fretIndex: 12 },
    ],
    "Fa": [
      { name: "Fa", octave: 2, midi: 41, stringIndex: 0, fretIndex: 1 },
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
    ],
    "Fa♯": [
      { name: "Fa♯", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
    ],
    "Sol♭": [
      { name: "Sol♭", octave: 2, midi: 42, stringIndex: 0, fretIndex: 2 },
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi𝄫", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi𝄫", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
    ],
    "Sol": [
      { name: "Sol", octave: 2, midi: 43, stringIndex: 0, fretIndex: 3 },
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
    ],
    "Sol♯": [
      { name: "Sol♯", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Si♯", octave: 2, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa𝄪", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa𝄪", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
    ],
    "La♭": [
      { name: "La♭", octave: 2, midi: 44, stringIndex: 0, fretIndex: 4 },
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♭", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♭", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
    ],
    "La": [
      { name: "La", octave: 2, midi: 45, stringIndex: 1, fretIndex: 0 },
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♯", octave: 3, midi: 56, stringIndex: 3, fretIndex: 1 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♯", octave: 4, midi: 68, stringIndex: 5, fretIndex: 4 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
    ],
    "La♯": [
      { name: "La♯", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Si♯", octave: 2, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Do𝄪", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi♯", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol𝄪", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si♯", octave: 3, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Do𝄪", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi♯", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol𝄪", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
    ],
    "Si♭": [
      { name: "Si♭", octave: 2, midi: 46, stringIndex: 1, fretIndex: 1 },
      { name: "Do", octave: 3, midi: 48, stringIndex: 1, fretIndex: 3 },
      { name: "Ré", octave: 3, midi: 50, stringIndex: 2, fretIndex: 0 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa", octave: 3, midi: 53, stringIndex: 2, fretIndex: 3 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La", octave: 3, midi: 57, stringIndex: 3, fretIndex: 2 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do", octave: 4, midi: 60, stringIndex: 4, fretIndex: 1 },
      { name: "Ré", octave: 4, midi: 62, stringIndex: 4, fretIndex: 3 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa", octave: 4, midi: 65, stringIndex: 5, fretIndex: 1 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La", octave: 4, midi: 69, stringIndex: 5, fretIndex: 5 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
    ],
    "Si": [
      { name: "Si", octave: 2, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Do♯", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Ré♯", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Mi", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Fa♯", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "Sol", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "La♯", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Si", octave: 3, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Do♯", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Ré♯", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Mi", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Fa♯", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "Sol", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "La♯", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Si", octave: 4, midi: 71, stringIndex: 5, fretIndex: 7 },
    ],
    "Do♭": [
      { name: "Do♭", octave: 3, midi: 47, stringIndex: 1, fretIndex: 2 },
      { name: "Ré♭", octave: 3, midi: 49, stringIndex: 1, fretIndex: 4 },
      { name: "Mi♭", octave: 3, midi: 51, stringIndex: 2, fretIndex: 1 },
      { name: "Fa♭", octave: 3, midi: 52, stringIndex: 2, fretIndex: 2 },
      { name: "Sol♭", octave: 3, midi: 54, stringIndex: 2, fretIndex: 4 },
      { name: "La𝄫", octave: 3, midi: 55, stringIndex: 3, fretIndex: 0 },
      { name: "Si♭", octave: 3, midi: 58, stringIndex: 3, fretIndex: 3 },
      { name: "Do♭", octave: 4, midi: 59, stringIndex: 4, fretIndex: 0 },
      { name: "Ré♭", octave: 4, midi: 61, stringIndex: 4, fretIndex: 2 },
      { name: "Mi♭", octave: 4, midi: 63, stringIndex: 4, fretIndex: 4 },
      { name: "Fa♭", octave: 4, midi: 64, stringIndex: 5, fretIndex: 0 },
      { name: "Sol♭", octave: 4, midi: 66, stringIndex: 5, fretIndex: 2 },
      { name: "La𝄫", octave: 4, midi: 67, stringIndex: 5, fretIndex: 3 },
      { name: "Si♭", octave: 4, midi: 70, stringIndex: 5, fretIndex: 6 },
      { name: "Do♭", octave: 5, midi: 71, stringIndex: 5, fretIndex: 7 },
    ],
  },
};
